//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Black21
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public int Card_No { get; set; }
        public string Player { get; set; }
        public string Dealer { get; set; }
    }
}
