//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Black21
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionReport
    {
        public int GameID { get; set; }
        public string PlayerTotal { get; set; }
        public string DealerTotal { get; set; }
        public string GameResult { get; set; }
    }
}
